### ISSUE TITLE
New Feature: Values

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#102]
we have made numericalLabels public facing, and an option in preferences. 

Show numerical labels 

This query parameter would add: 
- [x] Numerical labels to axes
- [ ] Numerical label to slope of tangent line at point on f(x) curve
- [ ] Numerical label of y-value at point on integral curve

Style the tangent and integral labels similar to Number Line sims, Area Model sims, Graphing Quadratics, and Graphing Lines (use NumberDisplay)

**Comment by pixelzoom** [comment]
@amanda-phet we need more specifics on this before proceeding.  Specifically:

(1) How do you want this to appear in the control panel? A checkbox labeled "Values", like in Hooke's Law? (see below) Something else? 

<img width="262" alt="screenshot_1957" src="https://user-images.githubusercontent.com/3046552/202039722-529d81fc-8150-4817-b7ea-9af74cc8da3c.png">

(2) What does the control look like in the Preferences dialog? An on/off switch?  How should it be labeled? How should it be formatted? Is a description shown? Should it match the style of any other Preferences controls? (It's currently an unlabeled on/off switch, with no description.)

(3) What do you want the Property name to be? It will appear in Studio under  `calculusGrapher.global.model.preferences`.

(4) What do you want the query parameter name to be? type? default value?  Ideally is should match the Property name, and make it easy for the user to related to the Preferences control. (It's currently named `numericalLabels`, boolean, default=false.)

**Comment by pixelzoom** [comment]
My recommendations for the questions in https://github.com/phetsims/calculus-grapher/issues/102#issuecomment-1315963860 is:

(1) Checkbox labeled "Values"

(2) An on/off switch with "Values" to the _right_ of the switch.

(3) `valuesVisibleProperty`

(4) `?valuesVisible`, boolean, default=false

**Comment by pixelzoom** [comment]
I took the liberty of implementing my recommendation from https://github.com/phetsims/calculus-grapher/issues/102#issuecomment-1315967743, since it's consistent with what I've done in other sims.  This will give a starting point to discuss changes.

Here's the current state of things...

Preferences dialog:

<img width="743" alt="screenshot_1958" src="https://user-images.githubusercontent.com/3046552/202044910-afa87240-b9b7-4f7f-8c1c-2390f2289d59.png">

Studio tree:

<img width="270" alt="screenshot_1960" src="https://user-images.githubusercontent.com/3046552/202045312-0d17dd22-e1b9-41f2-9622-347c627ade5a.png">

Associated Property in Studio:

<img width="562" alt="screenshot_1959" src="https://user-images.githubusercontent.com/3046552/202045021-00291ff4-346b-4cb8-ac2e-08fca22ba50c.png">

Query parameter:

```typescript
  /**
   * Shows numerical values wherever they appear in the sim: tick labels, tangent-line slope, etc.
   */
  valuesVisible: {
    type: 'boolean',
    defaultValue: false,
    public: true
  },
```

@amanda-phet @veillette what would you like to change?

**Comment by veillette** [comment]
The internal changes 2 and 3 brings it more in line with other sim.
 
```
(1) An on/off switch with "Values:" to the left of the switch, no description.

(2) valuesVisibleProperty

(3) ?valuesVisible, boolean, default=false
```

I'll let @amanda-phet review the more public facing change (1) .

**Comment by amanda-phet** [comment]
This is fine for now. 

Eventually we might style it differently an include some help text, so I think this can be closed.
