### ISSUE TITLE
Polish size of graphs and spacing around graphs

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/calculus-grapher#135]
Related to https://github.com/phetsims/calculus-grapher/issues/104

Ideally, I'd like the "total height" of all graphs, whether two or three, to be the same. I'm not sure if this is a worthwhile pursuit but one option could be to change the ranges. Another could be to adjust the spacing between graphs. 

The spacing between all graphs is currently inconsistent, so I propose starting with making it the same everywhere 
![image](https://user-images.githubusercontent.com/7852916/208744821-8aac1d48-aa86-460f-91c0-8fd6f7dc7fb8.png)

![image](https://user-images.githubusercontent.com/7852916/208744946-f3aafe68-c89e-4b7d-9ef5-09dd01b1bdb9.png)

![image](https://user-images.githubusercontent.com/7852916/208744986-0f72a652-c4da-4639-b291-416f41509ad9.png)

Then we could try seeing how it looks to have less spacing between graphs on the Lab screen, and more spacing on the other screens, and maybe that will help the overall look as you go between screens and scenes.

**Comment by pixelzoom** [comment]
Imo, we should wait to adjust overall layout until the "tangent" and "areas" accordion boxes are present.

**Comment by veillette** [comment]
Although it would be good to find out why the spacing between graphNode is inconsistent.
After all it should be a difference of 10 coordinates between each graph.
```js
      for ( let i = 1; i < numberOfVisibleGraphs; i++ ) {
        content[ i ].x = content[ i - 1 ].x;
        content[ i ].top = content[ i - 1 ].bottom + 10;
      }
```

I suspect that there are additional graphical elements, in graphNode, besides the chart that have bounds that are larger than the chart, such as labels or ticks. Since these graphical elements dont have the same bounds from one graph to the other, the spacing looks inconsistent.  

It would be preferable to align all the graph nodes with respect to their internal chart.

**Comment by veillette** [comment]
In the previous commit, the graph height is used to lay out the graph. SInce this height is solely dependent on the number of graphs. SInce the first three screens have the same number of graphs, this gives a very consistent layout for all three screens.
The change in the code base is 
```js
    for ( let i = 1; i < numberOfVisibleGraphs; i++ ) {
        content[ i ].x = content[ i - 1 ].x;
        content[ i ].y = content[ i - 1 ].y + graphHeightProperty.value + 10;
      }
``` 

We still need to tackle the absolute positioning of the graph set, but that may need to come later, given that we still need to take into account the barometers in screens 1 and 2.

**Comment by veillette** [comment]
For reference, here's a screenshot with the updated spacing.
![Calculus Grapher screenshot (19)](https://user-images.githubusercontent.com/7633344/209165722-ef9b9e39-182e-4625-9114-0dac42bc7ae3.png)

**Comment by pixelzoom** [comment]
Looks very nice! Consider adding a bit more margin to the left of the control panels. Or maybe centering the control panels between `graphsNode.right` and `layoutBounds.right`.

**Comment by veillette** [comment]
The work on long strings in #160 means that we are at a good point to address this issue.

**Comment by veillette** [comment]
Assigning to @amanda-phet to see if she has more requests regarding sizes and spacing.

**Comment by amanda-phet** [comment]
Some things still feel a little off. I think it would be best if we could do a quick call with @pixelzoom to look at some things together.

**Comment by pixelzoom** [comment]
Self assigning to take a look.

**Comment by pixelzoom** [comment]
I made a bunch of polishes to layout, spacing, and margins in the above commits. Note that they were initially associated (incorrectly) with #95.

**Comment by pixelzoom** [comment]
Design meeting: Fixes a couple of things. All polished. Closing.
