### ISSUE TITLE
Cleanup `tangentTool` and `areaUnderCurveTool`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#142]
To clean up some complication caused by using the same model and view elements for the `tangentTool` and `areaUnderCurveTool`:

* Create separate elements for `tangentTool` and `areaUnderCurveTool`, instead of having one `scrubber` (model) and `scrubberNode` (view) with overloaded semantics and complicated logic for `visibleProperty` and `fill`.

* Add options to CalculusGrapherModel:  `hasTangentTool?: boolean` and `hasAreaUnderCurveTool?: boolean`.  Use these to conditionally instantiate (or instrument?) the model and view elements.

**Comment by veillette** [comment]
The previous commit goes way beyond the clean up suggested by @pixelzoom.

This is a major refactor of all elements associated with `tangentTool` and `areaUnderCurveTool`.

Three new Classes have been created : A base Class `AncillaryToolNode`, and two child classes: `AreaUnderCurveToolNode` and `TangentToolNode`.

These three classes are responsible for all elements associated with `tangentTool` and `areaUnderCurveTool`, including the checkbox in the control panel.

`AreaUnderCurveToolNode` is instantiated in the `IntegralScreenView` whereas `TangentToolNode` is instantiated in the `DerivativeScreenView` 

`AreaUnderCurveTool` is instantiated in the `IntegralModel` whereas `TangentTool` is instantiated in the `DerivativeModel` 

As a result, this circumvents any conditional instantiations or instrumentations. 

It cleans up very cleanly the rather complicated logic that existed to control the visibility of various elements.
 
In order for the tandem tree structure to appear as the same as before, the tandem of the controlPanel, visibleProperties, and originalGraphNode were passed in. 

For instance, in order to create an additional checkbox in the control panel, `AncillaryToolNode` invokes
```` js
 // add ancillaryTool checkbox to the bottom of the main control panel
    controlPanel.addCheckbox( this.ancillaryToolCheckboxProperty,
      new RichText( options.checkboxStringProperty, {
        font: CalculusGrapherConstants.CONTROL_FONT
      } ), {
        visibleProperty: DerivedProperty.not( predictModeEnabledProperty ),
        tandem: controlPanel.tandem.createTandem( `${ancillaryTool.tandem.name}Checkbox` )
      } );
````

Visually, there should not be any changes except for the change of strings. The name of the checkbox and barometer is now decoupled for the area under the curve.

````JSON
  "checkbox.areaUnderCurve": {
    "value": "Area under Curve"
  },
  "barometer.areaUnderCurve": {
    "value": "Area under <br> Curve"
  }
````

**Comment by veillette** [comment]
@pixelzoom :Pinging as to be discussed at our next meeting.

**Comment by pixelzoom** [comment]
Self-assigning to review.

**Comment by veillette** [comment]
My previous comment regarding the view of the TangentToolNode and AreaUnderCurveToolNode make a bit of a mess for this issue, since the initial issue is about the model component. 

None of the work on the model has been done yet.

**Comment by veillette** [comment]
Unassigning @pixelzoom as there is nothing to review yet.

**Comment by pixelzoom** [comment]
At our 1/10/2022, I volunteered to look at issues related to AncillaryTool. So self-assigning.

**Comment by pixelzoom** [comment]
@veillette I think we can close this issue, since it's covered by https://github.com/phetsims/calculus-grapher/issues/144.   If you agree, please close. Otherwise let's discuss in our weekly meeting.

**Comment by veillette** [comment]
Closing.
