### ISSUE TITLE
Create separate classes for ReferenceLineNode, VerticalLineNode, PointLabelNode

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#151]
As a first step to support the issue #144, we should eagerly divide the responsibilities of VerticalLineNode. After #144, we can revisit after #144, if we should create a base class for ReferenceLineNode and VerticalLineNode.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/calculus-grapher/issues/153, so self assigning.

**Comment by pixelzoom** [comment]
I'm adding PointLabel and associated cleanup to this issue.

**Comment by pixelzoom** [comment]
@veillette FYI... The above commits made several important changes/fixes for "point label":

* Named the model element `PointLabel` and the view element `PointLabelNode` throughout, including tandem names.
* Got rid of fields in  PointLabelNodeOptions that were unused.
* Moved some code from GraphsNode to PointLabelNode
* Moved creation of PointLabelNode instances from GraphsNode to OriginalGraphNode, since they were previously being created by calling `originalGraphNode.addPointLabel`.
* Fixed a problem where changing xProperty moved the point, but not the text.
* At the x-min and x-max, the point and text were being clipped because the PointLabelNodes were being added to `curveLayer`.  So I made a separate `pointLabelNodesLayer` for PointLabelNodes.  This looks much nicer.

**Comment by pixelzoom** [comment]
I'm going to close this issue, because it's mostly covered in https://github.com/phetsims/calculus-grapher/issues/144.
