### ISSUE TITLE
Make font larger for point label

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#167]
In discussion with @amanda-phet, we wanted to make the font larger for the point lables. It's a bit tiny, only 10 point.  When I did this, the label overlapped the point, so there's something about the layout that must be hardcoded to 10-point font.  I'll investigate. 

We'd like to try 16-point (same as VerticalLine labels), but might also try 14-point for both the point and vertical line labels.

**Comment by pixelzoom** [comment]
Done in the above commit. Font for point labels is now 16, the same as vertical line labels.  I think 16-point looks nice, especially when accounting for mobile platforms (iOS, iPadOS). 

@amanda-phet how does this look to you? 

<img width="710" alt="screenshot_2150" src="https://user-images.githubusercontent.com/3046552/212158119-df5f7efb-bec4-493a-9e2e-949926564fab.png">

**Comment by amanda-phet** [comment]
I played with this for a while and it's looking great to me. The main concern I have with the larger size, which I just want to document here, is that the distance from the point could be an issue with points that are close (and thus the label can be unclear). However, it doesn't seem like a desirable scenario, for an instructional designer to use this tool and have points this close together. 

![image](https://user-images.githubusercontent.com/7852916/214460080-85122e3e-0c97-41e3-80a2-446292738d7d.png)

![image](https://user-images.githubusercontent.com/7852916/214460208-992871d1-06c0-4fb0-8d64-efe6ba67dcaf.png)

Closing, since I think the point label font is still appropriate.
