### ISSUE TITLE
Improve usefulness of the scrubber tools

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#207]
@catherinecarter propose a design change related to pedagogical usefulness of the scrubber tools. The Slack thread is captured below. 

Assigning to @catherinecarter and @amanda-phet to clarify this design. Priority is high because this would be a significant change this late in the process.

---
Slack discussion 1/30/2023:

@catherinecarter
> @pixelzoom @veillette - since we were talking of functionality opportunities, I was wondering how much effort/time you think it might take to add a “lock” feature where the vertical cursor tool would lock with the scrubber tool so they could move together if activated? This would only be on the first two screens (derivative and integral). Not sure where the button would go, but in terms of coding, how much of a lift would this be?

@pixelzoom
> The UI issues and design discussions required are probably a bigger lift than the development time.

@pixelzoom
> If you’re going to lock 2 things together, then their controls should be right next to each other, grouped (maybe with a bracket?), and the lock right next to the group. Something like:

![IMG_8547](https://user-images.githubusercontent.com/3046552/215594951-04d3a063-d74f-408e-a01e-e42ce05e6343.jpg)

@pixelzoom 
> Can I ask… what is the advantage of locking them together? I’m guessing it’s to have a vertical line.  Instead of locking together, could we have a vertical (dashed?) line that’s associated with the scrubbers, and extends through all graphs?

@catherinecarter 
> I was thinking that if they were locked, as you moved the cursor tool, if the tangent line moved with it, it would facilitate a discussion of seeing the tangent and the slope of the tangent simultaneously. The tangent feature shows the tangent, and the cursor tool can show the y-value for the same x-tool, but locking them would integrate the functionality of both. Seems like a valuable pedagogical tool.

@pixelzoom 
> Agreed. But locking feels like a really messy UX.

@catherinecarter 
> Your idea of having another vertical line be attached to the scrubber might be an interesting idea that would accomplish the same thing.

@pixelzoom
> For the scrubber, is there any reason to see the ‘x = value’ display? (like the reference line tool)

@catherinecarter
> Hm, would have to think about that one, and have 

@amanda-phet 
> chime in on that one. Seems like the reference line x-value is sufficient, but that’s my gut answer.

@amanda-phet 
> I see value in this kind of tool, but I just realized- we are using a dot on f’(x) to do this exact coordinating between graphs. Do you think the dot isn’t working well enough?

@catherinecarter 
> The dot is probably fine, I have just found myself moving either the reference line or the scrubber, and wishing they were connected a couple of times.

@pixelzoom 
> The dots are not always visible on the curves — sometimes they are outside the chart bounds. A faint vertical line might help tie them together?

@amanda-phet 
> Yeah, I am wondering if the solution to Cathy’s idea is not to lock the two tools, but actually to use a dashed vertical line instead of the point on f’(x) (edited) 

@catherinecarter 
> That’s interesting.

@amanda-phet 
> It might be a lot of lines.. just thinking about the two curves, the tangent line, the vertical line, but just throwing it out there. This is a tough UX problem, I agree, and am open to epxloring it some more. I have to head out but will keep thinking about it.

**Comment by veillette** [comment]
We will prototype it by adding a (faint) line attached to the scrubber. Assigned to @pixelzoom .

**Comment by pixelzoom** [comment]
This feature is ready for review by @catherinecarter and @amanda-phet.  @veillette FYI.

The screenshot below shows an example of what it looks like in the Derivative and Integral screens.

Questions:
* Does this address the need that you had in mind?
* If so, what would you like to change?

A few notes:
* The line is unfortunately _in front of_ the scrubber handle and points on the curves. This could not be avoided, because the scrubber and points are part of specific graphs, and the line spans all graphs.  It's a pretty subtle overlap -- if we can live with it, great.  If not, it's going to be an expensive change.
* I used a dash line to alleviate the previous problem a bit. I also think the dashed line works better when the grid is on.  The dash pattern is `[ 6, 6 ]`.
* The dashed line extends above/below the graphs just a tad. If we can live with this, great. If not, it's fixable, but costly.
* The dashed line width is 0.5, to make it a bit more subtle.  For reference, major grid lines have width 1, minor grid lines 0.5.
* The dashed line color is `rgb( 170, 170, 170 )`.  If you'd like to experiment with it, see `scrubberLineStroke` in the phetmarks Color Editor.  If you'd like the line to be somehow color-code to one of the curves, that will be a programming change.
 
<img width="1001" alt="screenshot_2291" src="https://user-images.githubusercontent.com/3046552/217404819-e5d2c21c-5b25-467e-bf3d-bd2849bca386.png">
<img width="1019" alt="screenshot_2292" src="https://user-images.githubusercontent.com/3046552/217404837-8e5a2cdb-0c7a-4314-b9d5-c505798421c4.png">

**Comment by pixelzoom** [comment]
> * The line is unfortunately _in front of_ the scrubber handle and points on the curves. ...

I should point out that this is true of all tools that involve a vertical line that spans all graphs. The screenshot below shows 3 such tools, all overlapping the tangent scrubber handle.  From left to right the lines are "vertical line C", the scrubber line, and the reference line.

<img width="873" alt="screenshot_2293" src="https://user-images.githubusercontent.com/3046552/217408575-8758d50d-dbdd-45bb-b36e-64ed227b1108.png">

**Comment by catherinecarter** [comment]
I agree the three lines together is distracting and the faint dotted line gets lost, but I do like the dotted line connecting the two graphs. For me, it makes the connectedness of the graphs more obvious, and it seems easier for my eye to track the points simultaneously. 
In terms of the line being in front of the scrubber, it almost makes it look like the scrubber might not be an active tool, but it doesn't bother me a ton. I am interested to hear what @amanda-phet thinks, since I am still learning about the implications of extra cost and such.

**Comment by pixelzoom** [comment]
> I agree the three lines together is distracting and the faint dotted line gets lost, ...

I was not offering that as a criticism.  I think it's totally fine, because each line is different and distinguishable.  And if the user feels that there are too many lines, they can easily turn some off.

**Comment by pixelzoom** [comment]
In case you'd like to review a dev version: https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.11/phet/calculus-grapher_all_phet.html

**Comment by pixelzoom** [comment]
@amanda-phet I really need your input on this, to know (1) are we keeping this feature? and if so (2) which of the nits identified in https://github.com/phetsims/calculus-grapher/issues/207#issuecomment-1421803317 need to be addressed.

**Comment by amanda-phet** [comment]
Before I even saw that you listed it out, I would've asked that the line go behind the scrubber handle, and that they stop at the edges of the graphs. The limitation with the start and end points of the line I can live with. I'm not sure I can get over having the line in front of the scrubber handle... 

I personally find it to be a lot of visual information to have the points AND the vertical line. If a vertical line is better, I'd want to see how it looks without the small points on the curves. 

My vote would be to publish two versions for interviews so we can compare how students handle the two options. 

I'd also like @ariel-phet 's input on this.

**Comment by amanda-phet** [comment]
@pixelzoom and I were playing with just a line, no points. We like this red version- while it still covers the scrubber, it is less noticeable. 

![image](https://user-images.githubusercontent.com/7852916/218808538-df98c079-a575-4b6f-9c11-46e4fbde9c93.png)

I think we should decide on point only or line only, not both. @catherinecarter what do you think?

**Comment by amanda-phet** [comment]
This is my favorite solution: 

![image](https://user-images.githubusercontent.com/7852916/218815483-665bf02f-1e15-4895-92fa-9f2f01fc210f.png)

I like that this does a few things. 
(1) We have a vertical line to make it easier to track between graphs, which @catherinecarter expressed was useful.
(2) We removed the clutter of activity happening on f(x) 
(3) We have a point on the red and green curves, which is conceptually important. The value at that point is related to something happening at f(x), which we are communicating with the tangent line and area under the curve. We don't really need a point on f(x) for this, because the value at that point isn't what we should be focusing on. We should be focused on the slope of that tangent and the cumulative area.

**Comment by pixelzoom** [comment]
@amanda-phet your favorite solution is implemented in the above commit.

Remaining warts:
* Vertical dashed line is in front of scrubber handle. This is a little less noticable now that the dashed line is color-coded to the scrubber.  If we need to address this, I can draw the dashed line in 2 segments (above and below the scrubber)
* The dashed line still extends a little above/below the graph rectangles.  This needs to be addressed for #95, so it will be perfect soon :)

**Comment by pixelzoom** [comment]
I have fixed the bit of dashed line that extends above/below the graphs, see below:

<img width="391" alt="screenshot_2310" src="https://user-images.githubusercontent.com/3046552/218862417-680ce481-9b23-4fc4-a966-17e95fc89107.png">

**Comment by catherinecarter** [comment]
Re: Color change
- The color change of the vertical line connecting the two graphs is great! It's nice that it's the same color as the graph of interest. I agree it also makes it less noticeable to be in front of the scrubber tool. 

Re: Points on f(x) and the other graphs. I'm on the fence about removing the point from f(x). 
- On the derivative screen, the point of interest (as @amanda-phet pointed out above) is really on f'(x), so on the one hand, drawing the user's eye to that graph is important and useful. On the other hand, the point on f'(x) is directly related to f(x) since the red dot is exactly the slope on f(x) at that point. So it seems like the point on f(x) would also be useful and important to highlight.
- On the integral screen, the point on f(x) seems less important since the green dot on the integral graph is representing the cumulative area from f(x). Even though it's up to that point, it's an accumulated value rather than an exact point of interest tied to f(x) like the derivative screen.

In general, it feels like with one point on the derivative or integral graph and no point on f(x), the point almost indicates precision. With the point gone on f(x), will this imply the f(x) graph is less precise? Perhaps, perhaps not, but that's what it made me think of. The clutter of having both the point and the vertical line connecting the graphs doesn't bother me, but perhaps in interviews this will be revealed.

**Comment by pixelzoom** [comment]
In the above commit, I was able to remove the overlap of the dashed line for the Integral screen scrubber. This was relatively easy because the scrubber is on the bottom graph, so I just shorten the line a bit in that case.  It looks nice now:

<img width="201" alt="screenshot_2311" src="https://user-images.githubusercontent.com/3046552/218874248-fc9f7245-edf8-4035-9ab4-40b260852e9e.png">

Overlap on the Derivative screen is still present, see below. This will be expensive to address, because it would involve splitting into 2 lines, and will therefore require an almost-entirely different implemention.  My recommendation is to live with this -- I doubt anyone will notice, especially since the dashed line is now red.   

I'm also not going to put more time into this until I hear that we are definitely keeping this feature. I have not heard a final decision on that yet.  So labeling for discussion at this Thursday's design meeting.

<img width="293" alt="screenshot_2312" src="https://user-images.githubusercontent.com/3046552/218874390-68b5120c-1298-409c-8cb3-0e12f3c79e9e.png">

**Comment by amanda-phet** [comment]
To solve the dashed line covering the scrubber handle, we like the idea of moving this scrubber to the bottom of the derivative graph. 

This also solves a potential touch problem- the user's hand could be covering f'(x) while using this scrubber. 

Discussed having the point on f(x) on the Derivative screen... what we are calculating is "slope AT THAT POINT" and by not having the point, we lose some precision. On the other hand, we like that the focus is on the slope of the TANGENT LINE, and the focus being on that line. 

Let's see how it feels when we move the scrubber down.

**Comment by amanda-phet** [comment]
Let's all remove the accumulated red line to the left of the red scrubber.

**Comment by pixelzoom** [comment]
TODO list for myself:

- [ ] Move the tangent scrubber to the bottom (derivative) graph
- [ ] Remove the "accumulation" line that appears to the left of the tangent scrubber

**Comment by pixelzoom** [comment]
@amanda-phet @catherinecarter (high-priority reply please) and anyone else who is interested... This is ready for review in https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.12/phet/calculus-grapher_all_phet.html.  A couple of screenshots are included below.

I like these changes very much. And the tangent scrubber is much more usable on touch devices (iPad, phone).

While the behavior here matches the desired behavior, I'll note that it took some hacking to get this to work. The current design has diverged enough from where we started that the implementation is longer appropriate for the design, and includes an acceptable level of chaos.  So if this is indeed what we want, I have a couple more hours of cleanup here.  But I'm blocked on that cleanup until we confirm that we always want the scrubber to be on the bottom graph. @amanda-phet please confirm.
 
<img width="1281" alt="screenshot_2315" src="https://user-images.githubusercontent.com/3046552/219526121-2970a63a-b07d-4b92-96d2-637b1a2b084c.png">
<img width="1279" alt="screenshot_2316" src="https://user-images.githubusercontent.com/3046552/219526132-131ed884-5575-4534-91d9-c36a1f3709e5.png">

**Comment by pixelzoom** [comment]
@amanda-phet a couple of related things:

(1) Should we add an icon (colored sphere) next to the "Tangent" and "Area Under Curve" checkbox labels.  This would be a nice cue.

(2) The initial position of the Area Under Curve scrubber is x=0.   So when I check the "Area Under Curve" checkbox, it's not as noticable as the tangent scrubber (which is initially at x=3).  Should it be at some more noticable intiial x position? Or would (1) make this less of an issue?

**Comment by catherinecarter** [comment]
I really like the scrubber on the bottom in the derivative graph. The consistency with the other graphs and scrubber lines is lovely. Putting the scrubber on the bottom so the connecting line doesn't overlap the sphere also makes it look much more interactive, and the single dot on f'(x) but not on f(x) is no longer a concern for me. Really like it! 

I've also wondered about the integral scrubber starting at x = 0 being noticeable. Theoretically, if students work with the derivative screen first, they will have already worked with a scrubber being activated by a toggle in the same location on each screen. So they are likely to notice it. But if students immediately go to the integral screen, they may not have had the experience. Since the integral is an accumulated area, started too far into the graph will diminish the conceptual understanding of accumulation. Maybe starting at x = 0.2 or something small would draw attention to it more but not diminish the concept?

**Comment by pixelzoom** [comment]
At 2/21/2023, @amanda-phet gave the go ahead for cleaning up the scrubber code.  I can assume that scrubbers will always be at the bottom of the screen.

@kathy-phet said:
> Regarding getting folks to move the scrubbers. We could also consider popping up one or two cuing arrows when the scrubber is activated, and then they go away forever if they have moved the scrubber on that screen.

I'd prefer not to do that.  The main reason is that we haven't had to do that in other math sims (graphing-quadratics, etc.) with this same style of manipulator.   The secondary reason is that cueing arrows are tricky for PhET-iO state. 

But this does bring up a point about the cursor for the scrubbers. We're currently using a hand cursor for the scrubbers.  In other sims where dragging is constrained to one dimension, we use a cursor that's specific to that dimension.  So I've changed the cursor to 'ew-resize', with is arrows like ↔.   Let me know what you prefer.
 
> I can go either way on putting the ball on the tangent and area check boxes (I think I prefer the cuing arrow that disappears, because the ball doesn't feel symbolic of the meaning)

I've added icons to the checkboxes, since it was easy, just to see if we like them or not.  I kind of like them, but don't feel strongly. 

> I do agree it feels a bit easy to miss the green scrubber since its at 0. I think Cathy's suggestion of starting at x=0.2 might also help a bit, so you can see the dashed line there and the ball easier

The area scrubber is not initially at x=0.2.

**Comment by amanda-phet** [comment]
I'm good with all of these decisions!

**Comment by pixelzoom** [comment]
Done done done. Lots of work here, much nicer. 

The class hierarchies now look like this:

```
Model:
AncillaryTool
    LabeledAncillaryTool
        LabeledLine
        LabeledPoint
    AreaUnderCurveScrubber
    ReferenceLine
    TangentScrubber

View:
LabeledLineNode
LabeledPointNode
ScrubberNode
    AreaUnderCurveScrubberNode
    ReferenceLineNode
    TangentScrubberNode
```

The major change is in the view. All of the scrubbers (including ReferenceLineNode) now share the same base class, and they are children of GraphsNode.

There were no PhET-iO changes required.

@veillette want to have a look? Let me know if you have questions.

**Comment by veillette** [comment]
@pixelzoom gave me an overview of the changes in the view at  our 3/8 meeting.  Closing.
