### ISSUE TITLE
Invisible Graphs can be interacted with.

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#270]
On Original graph, (and predict mode), we can make the graphs invisible  using the eye-toggle button. However, it is still possible to perform curve  manipulations while the graphs are hidden.

**Comment by veillette** [comment]
I am aware that this fall under the bug category but I personally could be a feature. It allows a teacher to manipulate a curve while hidden..

**Comment by pixelzoom** [comment]
Good catch.  No, I don't think the curve should be manipulatable when hidden.   I'll have a look.

**Comment by pixelzoom** [comment]
Ugh.   The correct way to address this is to make `originalGraphNode.inputEnabledProperty` a DerivedProperty, where one of the dependencies is `this.curveLayerVisibleProperty`.  That involves revisiting https://github.com/phetsims/calculus-grapher/issues/240, and making a PhET-iO API changed. 

Before I do that, I'm going to wait a bit, to see if another solution occurs to me. @veillette let me know if you have thoughts.

**Comment by pixelzoom** [comment]
I misspoke in https://github.com/phetsims/calculus-grapher/issues/270#issuecomment-1462491114.  We are not using  `originalGraphNode.inputEnabledProperty`. We instrumented `originalGraphNode.originalCurveNode.inputEnabledProperty`. 

After one false start in https://github.com/phetsims/calculus-grapher/commit/71c8f150d8b1dc94e237edbb9e2c9a50f466e8f2, the fix for this was a 1-liner in https://github.com/phetsims/calculus-grapher/commit/3b440e2f4ebb0fb413e6e7f6fc5006a093957005.  Over to @veillette to review, close if OK.

**Comment by veillette** [comment]
Good CLosing
