### ISSUE TITLE
 labeled points are visible when the plotted curve extends beyond the area of the graph 

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#280]
In https://github.com/phetsims/qa/issues/898, @stemilymill noted:

>Performance seems improved from dev.13. Even in phet-io standalone and with
?labeledLinesVisible=true&labeledPointsVisible=true , I noticed slightly less lagging in dev.21 while using the freeform tool than I did in the previous round of testing with dev.13.

>The only odd thing I did notice was that the labeled points are visible when the plotted curve extends beyond the area of the graph (github is not allowing me to add images again but i will attempt again later)

**Comment by veillette** [comment]
Here is a screenshot:
![Calculus Grapher screenshot (37)](https://user-images.githubusercontent.com/7633344/224722314-7652e0f6-80d4-476b-a0cb-3a2b9acf3aee.png)

**Comment by pixelzoom** [comment]
Ah yes, I remember seeing this in https://github.com/phetsims/qa/issues/898, then forgot about it. Thanks for breaking it out into a separate issue. 

I'm not clear on what's wrong with the above screenshot.  We had decided not to clip labeledPoints to the chartRectangle because of behavior at the left/right edges of the graph -- we don't want the labels to be clipped -- for example if someone want to label "Origin" at x=0.  And clipping the points themselves at (say) x=0 and x=10 is not a great look.

**Comment by pixelzoom** [comment]
Ah, I see.

Rather than clipping the points to the chartRectangle, I think we may need to derive their visibility based on whether their locations is within the range of the chartRectange.  Something like this (untested):

```ts
const xRange = ... // x-axis range of the ChartRectangle
const yRange = ... // y-axis range of the ChartRectangle
visibleProperty: new DerivedProperty(
  [ labeledPoint.visibleProperty, labeledPoints.xProperty, labeledPoint.yOriginalProperty ],
  ( visible, x, y ) => ( visible && xRange.contains( x ) && yRange.contains( y ) )
```

**Comment by pixelzoom** [comment]
Working on this now...

**Comment by veillette** [comment]
oops I didnt see your comment

**Comment by pixelzoom** [comment]
Looks like you already fixed it :)

**Comment by pixelzoom** [comment]
Looks like you already fixed it :)  Nice work!

<img width="815" alt="screenshot_2412" src="https://user-images.githubusercontent.com/3046552/224731942-707717a7-3d73-4875-b40a-53050b5709c6.png">

**Comment by veillette** [comment]
CLosing
