### ISSUE TITLE
Studio tree no longer shows dependencies for PatternStringProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#290]
Dependencies for PatternStringProperty have suddenly gone missing in the Studio tree.  I beleive that this is due to a bug introduced in https://github.com/phetsims/axon/issues/431#issuecomment-1468688856.   This is blocking for 3/20 QA dev testing.

**Comment by zepumph** [comment]
https://github.com/phetsims/axon/issues/431#issuecomment-1468688856 did not have work done on it.


After a poking around in general types, I see that there haven't been any changes in places like PatternStringProperty or getStringModule recently.

Looks like you have a usage of a PatternStringProperty being passed into a RichText as its stringProperty. The tandem is being put in the "values" object instead of the opions (third arg).

Hows that?

```diff
Subject: [PATCH] convert to NumberControl, https://github.com/phetsims/my-solar-system/issues/105
---
Index: js/common/view/preferences/PredictControl.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/preferences/PredictControl.ts b/js/common/view/preferences/PredictControl.ts
--- a/js/common/view/preferences/PredictControl.ts	(revision 65ec74f7a907af13318e8704772f9667d85d273d)
+++ b/js/common/view/preferences/PredictControl.ts	(date 1678830114541)
@@ -45,7 +45,8 @@
       } ) );
 
     const descriptionStringProperty = new PatternStringProperty( CalculusGrapherStrings.predictPreferenceDescriptionStringProperty, {
-      variable: CalculusGrapherPreferences.functionVariableProperty,
+      variable: CalculusGrapherPreferences.functionVariableProperty
+    }, {
       tandem: tandem.createTandem( RichText.STRING_PROPERTY_TANDEM_NAME )
     } );
     const descriptionText = new RichText( descriptionStringProperty, {

**Comment by pixelzoom** [comment]
Face palm.  Thanks @zepumph.  I have done this so... many... times.  In addition to fixing PredictControl.ts, I've added an assertion to PatternStringProperty to catch this mistake. 

Closing.
