### ISSUE TITLE
Add "off scale" indicator to barometers

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/calculus-grapher#300]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/921
The bar graph for the "Slope of Tangent" that appears when you enable the Tangent viewer in the first screen tops out at a high level, but not the highest it can easily go. This is also the case for the Area Under Curve on the second screen. I think it would be good to be able to zoom out on this graph, or at least have an indicator that the bar is now beyond the graph and not just not growing.

**Visuals**
![zoomoutslopetan](https://user-images.githubusercontent.com/41024075/226443988-4fb74a89-6802-4dc6-b071-afbfc8824e27.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Calculus Grapher‬
URL: https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25/phet/calculus-grapher_all_phet.html
Version: 1.0.0-dev.25 2023-03-20 03:37:03 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by veillette** [comment]
Let me tag @amanda-phet as we would need some design input about what to do if we decide to address it.

**Comment by pixelzoom** [comment]
I think it would be reasonable (and relatively straightforward) to add something to the barometer that indicates that the value beyond the range of the barometer.  Perhaps an arrow head that appears above/below the bar?   And I'm guessing that this may also apply to the "Net Signed Area" barometer.

I feel strongly that we should _not_ add zoom buttons to barmometers.

**Comment by pixelzoom** [comment]
Here are some examples of how applications like PowerPoint deal with a similar issue.   Since we're not showing the range of the y-axis, I was thinking that the top part of these bars would be more like a triangle.

We should also discuss what (if anything) needs to happen when "Values" preference is on.  I don't think we should show attempt to show the off-scale value --- we would need to resort to scientific notation, would need to decide on how many decimal places, etc.

<img width="365" alt="screenshot_2443" src="https://user-images.githubusercontent.com/3046552/226598488-e12c7399-e8df-4f2c-82fa-0d8e9c15f19a.png">
<img width="359" alt="screenshot_2444" src="https://user-images.githubusercontent.com/3046552/226598510-a34d5853-bb2f-430a-82ac-4db71628e807.png">
<img width="365" alt="screenshot_2443" src="https://user-images.githubusercontent.com/3046552/226598512-bd6e2308-801d-487d-939e-62fbc874a688.png">
<img width="443" alt="screenshot_2445" src="https://user-images.githubusercontent.com/3046552/226598519-e0344f29-c281-4dee-8699-5ae8cff82bb
<img width="406" alt="screenshot_2446" src="https://user-images.githubusercontent.com/3046552/226598528-e9e3e94b-d019-4f09-ba6f-4f46d266b857.png">
a.png">

**Comment by pixelzoom** [comment]
Here's the "off-scale" representation used in the _Micro_ screen of ph-scale.  I don't think we want to get this complicated, but he illustrates the use of an arrow head.

<img width="384" alt="screenshot_2447" src="https://user-images.githubusercontent.com/3046552/226600898-6630f71c-c21c-4590-a56e-e1666d533900.png">

**Comment by pixelzoom** [comment]
Here's what I had in mind for Calculus Grapher -- a very simply indicator that becomes visible above/below the bar when the value goes off scale.  It uses the same color as the bar, and (like the bar) is not stroked.  No value is shown.

<img width="292" alt="screenshot_2450" src="https://user-images.githubusercontent.com/3046552/226602735-13e8f3ea-c77e-4e3f-9ba9-74ae9bfb5cfc.png">

In context:

<img width="1129" alt="screenshot_2449" src="https://user-images.githubusercontent.com/3046552/226602360-a0dba974-ac39-45fa-88d0-f3b7acf5c97f.png">

**Comment by amanda-phet** [comment]
I would like to try either adding a few pixels of arrow "tail" to the triangle arrow head, OR if that's too hard to fit in, I'd like to try an arrow head that is the same width as the tail.

**Comment by pixelzoom** [comment]
I'll take this one.

**Comment by pixelzoom** [comment]
@amanda-phet this is ready for review.  If you have changes/polishes, please describe. Otherwise OK to close.

Summary of where this is currently at:

I started with a tiny bit of tail on the arrow heads.  Unfortunately, it creates an optical illusion, where the tail looks narrower than the bar, and not quite horizontally aligned.  Here are screenshots (zoomed in, and in context):

<img width="143" alt="screenshot_2458" src="https://user-images.githubusercontent.com/3046552/226921316-029a2c12-84bb-44c4-9435-db9ad4557eea.png">
<img width="1149" alt="screenshot_2459" src="https://user-images.githubusercontent.com/3046552/226921326-ce6597bd-a59c-463f-b5fe-09e55e51e0ba.png">

So @veillette and I experiemented with no tail on the arrows.  This looks a lot cleaner, eliminates the optical illusion, and feels equally as effective.  Here are screenshots (zoomed in, and in context):

<img width="141" alt="screenshot_2460" src="https://user-images.githubusercontent.com/3046552/226921523-8fc0fbd7-d5ab-4e1e-8092-41a1ab82f853.png">
<img width="1149" alt="screenshot_2461" src="https://user-images.githubusercontent.com/3046552/226921581-7928be9e-e898-4804-9d45-e658c6967751.png">

**Comment by amanda-phet** [comment]
Looks good to me. thanks!
