### ISSUE TITLE
Possible for netSignedAreaAccordionBox to extend offscreen with stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/calculus-grapher#306]
**Test device**
MacBook Air (and Dell)

**Operating System**
macOS 13.2.1

**Browser**
Safari 16.3

**Problem description**
For https://github.com/phetsims/qa/issues/921, on the Integral Screen with stringTest=dynamic it is possible for netSignedAreaAccordionBox to extend past the bottom of the screen when the title is very long. This is also seen in master. 

**Steps to reproduce**
1. add ?stringTest=dynamic to url
2. Go to the Integral Screen and check the Area Under Curve Checkbox
3. Press the right arrow 3 times.

**Visuals**
<img width="276" alt="Screenshot 2023-03-22 at 11 26 24 AM" src="https://user-images.githubusercontent.com/87318828/226957118-f21d3711-39c3-4927-acda-c222e1f2f4c8.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: lyrics
URL: https://phet-dev.colorado.edu/html/calculus-grapher/1.0.0-dev.25/phet/calculus-grapher_all_phet.html?stringTest=dynamic
Version: 1.0.0-dev.25 2023-03-20 03:37:03 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
Language: en-US
Window: 1337x710
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
I'll take this one. Multiline titles in accordion boxes need a `maxHeight`, similar to what I did in another issue for multiline checkbox labels.

I'll also look at setting a fixed height for the acccordion boxes.  But my understanding is that's not a requirement for anyrhing other than the English default strings.

**Comment by pixelzoom** [comment]
Fixed in the above commits, for both the "Net Signed Area" and "Slope of Tangent" accordion boxes, see screenshots below with `?stringTest=dynamic`.   The titles both have `maxWidth: 80` and `maxHeight: 40`.

Note that it's not required that these accordion boxes maintain a fixed height -- and that's also something that's not currently supported by AccordionBox common code.

Back to @Nancy-Salpepi for review, close if OK.

<img width="1147" alt="screenshot_2464" src="https://user-images.githubusercontent.com/3046552/227235459-cccf6c26-b382-4175-ac0a-2acc461f9649.png">
<img width="1138" alt="screenshot_2463" src="https://user-images.githubusercontent.com/3046552/227235481-63f958d7-623e-4ba3-a481-896ecb35c825.png">

**Comment by Nancy-Salpepi** [comment]
Looks good. Closing 🙂.
