### ISSUE TITLE
"Data: Textarea" wrapper is laggy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/calculus-grapher#313]
In https://github.com/phetsims/qa/issues/921#issuecomment-1480309971, @KatieWoe asked:

> The sim seems to be quite laggy when using the Data: Textarea wrapper. Is this a concern/worth an issue?

In https://github.com/phetsims/qa/issues/921#issuecomment-1481176943, @veillette replied:

> You are probably trying to change the curve points. There is a lot of meta data associated with a curve since all points have some metadata associated with them. You can create an issue though.

Indeed, the state for this sim is huge.

@zepumph @samreid What do you recommend for this?  Is the "Data: Textarea" wrapper supposed to be responsive?

**Comment by samreid** [comment]
I'm seeing 2-3 frames per second while dragging curves in the text area wrapper on Mac/Chrome for the dev version linked above. That seems fine to me. Even if it was 0.2 frames per second, that seems OK. It is not expected that outputting a large amount of streaming data to the DOM would be performant--clients would not want to leverage the data stream in that way.

**Comment by zepumph** [comment]
Noting a theme that our current exploratory PhET-iO feature tools (the wrapper suite) often cause explainable problems that may result in a client thinking that PhET-iO is buggy rather than just piping >5MB to a text area every frame. We should definitely design the client experience on feature set exemplars soon! (like with https://github.com/phetsims/phet-io-wrappers/issues/129)
