### ISSUE TITLE
Sizing of the derivative curve on home screen

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#322]
While working on https://github.com/phetsims/qa/issues/924
 
Operating System
Windows 10

Browser
Chrome

**Problem description**

On the Derivative Screen, create a curve so that the Tangent, when turned on, will be on the curve.
Check the Tangent checkbox.
Launch the sim.

As one toggles from `Leibniz` to `Lagrange` notation, one notices a change in the size of the curve of the derivative on the home screen.

![Calculus Grapher screenshot (67)](https://user-images.githubusercontent.com/7633344/228608505-5b9c9a66-5235-44d0-b0b8-2a82e67c2870.png)
![Calculus Grapher screenshot (68)](https://user-images.githubusercontent.com/7633344/228608519-a1128bd1-0848-41c5-9756-2b5a1bc4e851.png)

I'll note that the change is sizing is only apparent after careful analysis as the preference dialogue hides the home screen during the change. 
![image](https://user-images.githubusercontent.com/7633344/228611383-cd332010-1c3d-491c-b647-c4786065e18c.png)

**Comment by veillette** [comment]
I don't know if it is worth fixing as it is quite a subtle change, without a side by side comparison.

**Comment by pixelzoom** [comment]
ScreenIcon handles resizing of the content that it's provided.   Since df/dx is taller than f'(x), the entire icon content therefore gets scaled down.  If we wanted to curve portion of the icon to maintain a fixed size, that's going to require some more complicated code.  And the end result will be that the curve's fixed size is smaller, and f'(x) will be smaller -- which imo is not an improvement.   So my recommendation is to do nothing here.

**Comment by veillette** [comment]
Yes bigger is better. That is a sound reason not to address this. Closing.
