### ISSUE TITLE
CalculusGrapherCheckboxGroup

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#72]
There are two groups of checkboxes in this simulation. Having one class called CalculusGrapherCheckboxGroup is misleading/confusing.

**Comment by pixelzoom** [comment]
The group to the left of the graphs could be called CurvesCheckboxGroup, since it controls which curves are shown.

Some ideas for what to call the group to the right of the graphs: ToolsCheckboxGroup, AnnotationsCheckboxGroup, DecoractionsCheckboxGroup, ...  something that indicates that these are extra things that are added to the graphs.

**Comment by veillette** [comment]
Our work is done here. Closing.
