### ISSUE TITLE
Tilt and Shift behaviour with curvy graphs

### ISSUE THREAD

**Issue by phet-steele** [phetsims/calculus-grapher#8]
When dragging your mouse over a curve while trying to tilt or shift causes the graph to jump around. Presumably this is due to the mouse jumping between points on the curve. The best way to see this is to make a sine graph with small periods, then tilt and shift:

Tilt (notice it takes a second to find a point to grab and start manipulating, implying there is a space between points)
![calcgra2](https://cloud.githubusercontent.com/assets/5863899/7754904/6d51e82e-ffad-11e4-91f0-c9b642f1be99.gif)

Shift
![calcgra3](https://cloud.githubusercontent.com/assets/5863899/7754908/703612c2-ffad-11e4-9fb0-0f373a2df170.gif)

Tested on Win 8.1 FF

**Comment by bryo5363** [comment]
I noticed some other strange behavior with tilt, shift and sine. Initially I made a hill, tilted the graph and then shifted it down. When I add a sine wave, I get extremely sharp peaks when I drag the cursor upwards
![calculusgrapher2](https://cloud.githubusercontent.com/assets/7717368/7864009/d92abbd8-051c-11e5-9922-f265edc4db8d.gif)

**Comment by phet-steele** [comment]
This may be a long shot, but do you remember where on the line you grabbed when you tilted and shifted?

**Comment by bryo5363** [comment]
I believe it was right where my cursor was at the beginning of the gif. D you notice different behavior based on where you tilt and shift from?

**Comment by phet-steele** [comment]
Well I'm curious if the behavior I found in #11 happens elsewhere than tilting from the origin.

**Comment by bryo5363** [comment]
I also noticed that when dragging the sine wave while the line is tilted that there is a slight change in the frequency of the wave

![calculusgrapher5](https://cloud.githubusercontent.com/assets/7717368/7872347/8bd572b4-0554-11e5-876c-bc78a9c42e12.gif)

**Comment by amanda-phet** [comment]
Unassigning and putting on hold until this sim is ported.

**Comment by brandonLi8** [comment]
@amanda-phet FYI this is also an issue in master.

@phet-steele seems correct that this is " due to the mouse jumping between points on the curve." It's especially noticeable when you move your pointer horizontally.

----

One solution I thought about could be to only consider where the user **first** pressed the curve for the x-position of where to tilt the graph. Then, when the user moves the pointer around, only the y-displacement is considered for the tilt.

However, there are some consequences; the curve doesn't necessarily 'tilt' to the your pointer when you move horizontally from where the user first pressed the curve. I went ahead and tried it locally (not pushed)

and found that this made the tilting experience much worse and was not a good approach.
<details><summary> Sample: </summary>

![*](https://user-images.githubusercontent.com/42391580/87072521-24f01800-c1d9-11ea-9e31-4b05bbe41c45.gif)

</details>

**Comment by veillette** [comment]
As of 10/17/2022, this issue is not addressed in master, we have have a similar buggy behavior.
