### ISSUE TITLE
Notation preferences for curve labels

### ISSUE THREAD

**Issue by veillette** [phetsims/calculus-grapher#98]
We have a simple preference that uses t instead of x for the variable. 

Current: 
∫0→x f(t) dt
f(x) 
df/dx
d2f/dx2
---------

Time Base with Leibniz: 
∫0→t1 f(t) dt
f(t) 
df/dt
d2f/dt2

Space base with Lagrange
∫0→x1 f(x) dx
f(x) 
f’(x) 
f’’(x)

We are considering four options total (two binary options) that switch between 
space  (x) OR  time (t)
Lagrange (prime) OR Leibniz notations (fractions) 

We will decide on notation after @amanda-phet talks to math teachers.

**Comment by pixelzoom** [comment]
The first thing we need to decide is whether this is 1 Preference or 2 Preferences (1 or 2 Properties), and how that is presented in the Preferences dialog.   

The 1 Preferences approach has the advantages of a better UI, with the ability to add more notation choices in the future -- which may be needed since we have fully not decided what notation are needed.

UI for 1 Preference:
```
Notation:
O Leibniz: df/dx
O Leibniz: df/dt
O Lagrange: f’(x)
O  Lagrange: f’(t)
```

UI for 2 Preferences
```
Notation convention:
O Leibniz
O  Lagrange

Variable:
O x
O t
```

Assuming we want to initialize this via query parameter(s) (which has not been requested yet)... The 2 Preferences approach is a little clearer.  For example:

2 Preferences:

```
?notation=Leibniz&variable=x
?notation=Lagrange&variable=t
```

1 Preference:

```
?notation=xLeibniz
?notation=tLagrange
```

Note that try to have a 1:1 correspondence between query parameters and Preferences.  So it's not advisable to (for example) use 2 query parameters with 1 preferences setting.

@amanda-phet we need decision here before proceeding, because 1 Preference and 2 Preferences are very different implementations.

**Comment by pixelzoom** [comment]
I'll own this issue and discuss with @amanda-phet.

**Comment by amanda-phet** [comment]
We prefer the 2 preference UX

```
Notation:
O Lagrange (e.g. f'(x))
O Leibniz (e.g. df/dx) 

Variable:
O x
O t
```

1. We'd like Lagrange listed first, since that will be the default. 
2. We'd like an example included with the notation options, formatted appropriately. 
3. Can the example for each notation type be dynamic, so it would updated based on the variable selection?

**Comment by pixelzoom** [comment]
Screenshot below shows what is currently implemented.  

Caveats:
* Changing these preferences does NOT currently update the reset of the sim
* The Notation examples are ugly and need work.  

@viellette and I will discuss next steps in our meeting this week.

![screenshot_361](https://user-images.githubusercontent.com/3046552/203136339-16ac13d0-6df7-4465-b9b5-a5e8062f6a74.png)

**Comment by pixelzoom** [comment]
@amanda-phet please review.  Let me know what you like to change.  I intend to polish the notation examples, so assign back to me after review.

**Comment by pixelzoom** [comment]
@veillette and I decided to simplify the labeles for the Notation radio buttons, so that we can use the same Nodes to render the examples as we are using to label the charts.  Because these are Nodes, they cannot be in the middle of a string, like "(e.g. f'(x))".   Note also the left-to-right order of the label will not be flexible based on locale -- the example notation will always be to the right of the label.  @amanda-phet is this acceptable?

<img width="625" alt="screenshot_1977" src="https://user-images.githubusercontent.com/3046552/203402528-d5876d14-0087-42e6-b18f-8274fdf1a8c3.png">

**Comment by amanda-phet** [comment]
This looks great! I think it's fine that the example notation will always be to the right of the label. 

As far as improving the notation examples, it would be more ideal if the Leibniz example was a vertical fraction but I understand if that might be difficult and not worth the effort. Here's what I mean by vertical fraction: 
<img width="63" alt="image" src="https://user-images.githubusercontent.com/7852916/203415972-207df82b-a6c5-4143-a028-e5db749a442e.png">

I also want to note that the visual design of this dialog will likely change, from the outcomes of https://github.com/phetsims/joist/issues/842, but I'm ok if that happens later and I can open an issue at that time.

**Comment by pixelzoom** [comment]
> As far as improving the notation examples, it would be more ideal if the Leibniz example was a vertical fraction ...

The radio buttons here will use the same Node as is used to label the graphs.  When @veillette has those working for the graphs, we will use them here.  I'll be happy to handle that, or @veillette can address it if he wishes (so I'll co-assign him to this issue).

> I also want to note that the visual design of this dialog will likely change, ...

I'm expecting that to be the case for every sim that has sim-specific Preferences.

**Comment by veillette** [comment]
In the above commit, the notation of the labels in the dialog/preferences has been updated such that  (1) the  leibniz/lagrange notation examples have the same visual look as the rest of the sim and (2) the leibniz/lagrange notation is dynamical and get updated with a change of variable notation. 

![image](https://user-images.githubusercontent.com/7633344/204343856-d970d32c-3e45-4b2c-a2ea-5ba9192a739b.png)

Assigning to @amanda-phet for review.

**Comment by amanda-phet** [comment]
Looks great! And I like how it's dynamic- that seemed to be working well for me.

**Comment by veillette** [comment]
Thanks Amanda, we can close this issue, then.
